// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyrxrxoexmdgoselznaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5cnhyeG9leG1kZ29zZWx6bmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDYzNjEsImV4cCI6MjA2OTM4MjM2MX0.HxbR_cTzdyMVRDe6sgTVEuNga1PyuwEb-q30DQyG1ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});